language: rust
dist: trusty
sudo: true

rust:
  - stable
  - beta

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++-5
      - llvm-3.9-dev
      - libclang-3.9-dev
      - clang-3.9

script:
  - rm -f ~/.cargo/bin/libcache/librocksdb.a
  - cargo test --manifest-path=librocksdb-sys/Cargo.toml
  - cargo test

cache: cargo
